# JCB-GDAS format marine observations configuration
# This file contains observation type names that correspond to JCB-GDAS templates
# Based on GFS v17 observation list format

observations:
# ADT (Altimeter Data)
- rads_adt_3a
- rads_adt_j3
- rads_adt_sa

# SSS (Sea Surface Salinity)
- sss_smap_l2
- sss_smos_l2

# SST (Sea Surface Temperature)
- sst_viirs_npp_l3u
- sst_avhrrf_ma_l3u

# Sea Ice
- icec_amsr2_north
- icec_amsr2_south

# In situ
- insitu_temp_profile_argo
- insitu_salt_profile_argo
- insitu_temp_surface_drifter
