# Example marine observations configuration for CUSTOM TEMPLATE development
# This file demonstrates the format for developing custom Jinja templates
# For production use, prefer the JCB-GDAS format in example_observations_jcb.yaml

observations:
  - type: sst_generic
    input_path: ./data/marine
    input_prefix: ""
    input_suffix: .nc
    output_path: ./output/marine
    output_prefix: "diag_"
    output_suffix: _out.nc

  - type: insitu_temp_profile_argo
    input_path: ./data/marine
    input_prefix: ""
    input_suffix: .nc
    output_path: ./output/marine
    output_prefix: "diag_"
    output_suffix: _out.nc

  - type: adt_rads_all
    input_path: ./data/marine
    input_prefix: ""
    input_suffix: .nc
    output_path: ./output/marine
    output_prefix: "diag_"
    output_suffix: _out.nc
