# Additional context for JEDI 3DVAR configuration
# This file provides additional parameters for the variational analysis

# Time window configuration
window_begin: "2024-01-01T00:00:00Z"
window_length: "PT6H"
background_date: "2024-01-01T00:00:00Z"

# Model configuration
model_name: "MOM6"
model_tstep: "PT1H"

# Background ensemble configuration
ensemble_members: 20
background_template: "background_%mem%.nc"

# Variational algorithm parameters
outer_iterations: 10
gradient_norm_reduction: 1.0e-10

# Geometry and metadata
geometry_namelist: "input.nml"
fields_metadata: "fields_metadata.yaml"

# Output configuration
output_dir: "./output"
output_filename: "marine_analysis.nc"

# Optional: Enable LETKF application mode
letkf_app: false
